"""
state.py — Mutable runtime data stores for Lane4.

All values here are populated at startup by main.py's load_data() pipeline.
Use in-place mutations (dict[key]=val, list.append, list.clear) to keep
references valid across all modules that import from here.

Do NOT rebind these names (e.g., BENCHMARKS = {} in another module) — that
creates a new object and severs the connection for all other importers.
"""
import os
import json

# ── PRIMARY UNIVERSE (source of truth) ──────────────────────────────────────
# EXPLORE_SCHOOLS is the canonical 324-school swimming universe.
# Built at startup from output/lane4_snapshot_compatible.csv.
# Every endpoint that needs a school list starts here — never from TEAMS_LIST.
EXPLORE_SCHOOLS = []   # [{school, conference, conf_tier_short, meta, hasSwimData, …}]

# ── ENRICHMENT SOURCES (read-only after startup) ─────────────────────────────
BENCHMARKS = {}    # "Conference|Event" -> {first, eighth, sixteenth, sec_per_place}
TEAMS = {}         # "Conference|School" -> enrichment record (PSF, tier, finish)
TEAMS_LIST = []    # flat list of TEAMS records — enrichment only, not the universe
CONFERENCES = {}   # conference name -> sorted list of canonical school names
NORMALIZATION_LOG = []  # records every name-normalization applied during load

# Pre-computed lat/lng for all 324 schools (generated by generate_school_locations.py).
# Never geocode live — always serve from this dict.
_school_locs_path = os.path.join(os.path.dirname(__file__), 'output', 'school_locations.json')
SCHOOL_LOCATIONS = {}
if os.path.exists(_school_locs_path):
    with open(_school_locs_path, encoding='utf-8') as _f:
        SCHOOL_LOCATIONS = json.load(_f)
