// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lane4-dark-refined/DarkCommand.tsx": () => import("../components/mockups/lane4-dark-refined/DarkCommand.tsx"),
  "./components/mockups/lane4-dark-refined/DarkPolished.tsx": () => import("../components/mockups/lane4-dark-refined/DarkPolished.tsx"),
  "./components/mockups/lane4-refined/ConfidentPro.tsx": () => import("../components/mockups/lane4-refined/ConfidentPro.tsx"),
  "./components/mockups/lane4-refined/CrispElevated.tsx": () => import("../components/mockups/lane4-refined/CrispElevated.tsx"),
  "./components/mockups/lane4-dark-vibes/ChromeAthletic.tsx": () => import("../components/mockups/lane4-dark-vibes/ChromeAthletic.tsx"),
  "./components/mockups/lane4-dark-vibes/NightAthletic.tsx": () => import("../components/mockups/lane4-dark-vibes/NightAthletic.tsx"),
  "./components/mockups/lane4-dark-vibes/VoidPrecision.tsx": () => import("../components/mockups/lane4-dark-vibes/VoidPrecision.tsx"),
  "./components/mockups/lane4-vibes/DarkAthletic.tsx": () => import("../components/mockups/lane4-vibes/DarkAthletic.tsx"),
  "./components/mockups/lane4-vibes/PlayfulFriendly.tsx": () => import("../components/mockups/lane4-vibes/PlayfulFriendly.tsx"),
  "./components/mockups/lane4-vibes/WarmAuthority.tsx": () => import("../components/mockups/lane4-vibes/WarmAuthority.tsx")
};
